from django.urls import path

from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.overview, name="overview"),
    path("search/", views.search, name="search"),
    path("clients/", views.ClientListView.as_view(), name="client_list"),
    path("clients/create/", views.ClientCreateView.as_view(), name="client_create"),
    path("clients/<int:pk>/", views.ClientDetailView.as_view(), name="client_detail"),
    path("clients/<int:pk>/edit/", views.ClientUpdateView.as_view(), name="client_update"),
    path("clients/<int:pk>/delete/", views.ClientDeleteView.as_view(), name="client_delete"),
    path("projects/", views.ProjectListView.as_view(), name="project_list"),
    path("projects/create/", views.ProjectCreateView.as_view(), name="project_create"),
    path("projects/<int:pk>/", views.ProjectDetailView.as_view(), name="project_detail"),
    path("projects/<int:pk>/edit/", views.ProjectUpdateView.as_view(), name="project_update"),
    path("projects/<int:pk>/delete/", views.ProjectDeleteView.as_view(), name="project_delete"),
    path("sites/", views.HostedWebsiteListView.as_view(), name="site_list"),
    path("sites/create/", views.HostedWebsiteCreateView.as_view(), name="site_create"),
    path("sites/<int:pk>/", views.HostedWebsiteDetailView.as_view(), name="site_detail"),
    path("sites/<int:pk>/edit/", views.HostedWebsiteUpdateView.as_view(), name="site_update"),
    path("sites/<int:pk>/delete/", views.HostedWebsiteDeleteView.as_view(), name="site_delete"),
    path("invoices/", views.InvoiceListView.as_view(), name="invoice_list"),
    path("invoices/create/", views.InvoiceCreateView.as_view(), name="invoice_create"),
    path("invoices/<int:pk>/", views.InvoiceDetailView.as_view(), name="invoice_detail"),
    path("invoices/<int:pk>/edit/", views.InvoiceUpdateView.as_view(), name="invoice_update"),
    path("invoices/<int:pk>/delete/", views.InvoiceDeleteView.as_view(), name="invoice_delete"),
    path("invoices/<int:pk>/generate-pdf/", views.generate_invoice_pdf, name="invoice_generate_pdf"),
    path("time-entries/", views.TimeEntryListView.as_view(), name="timeentry_list"),
    path("time-entries/create/", views.TimeEntryCreateView.as_view(), name="timeentry_create"),
    path("time-entries/<int:pk>/edit/", views.TimeEntryUpdateView.as_view(), name="timeentry_update"),
    path("time-entries/<int:pk>/delete/", views.TimeEntryDeleteView.as_view(), name="timeentry_delete"),
    path("attachments/", views.FileAttachmentListView.as_view(), name="attachment_list"),
    path("attachments/create/", views.FileAttachmentCreateView.as_view(), name="attachment_create"),
    path("attachments/<int:pk>/", views.FileAttachmentDetailView.as_view(), name="attachment_detail"),
    path("attachments/<int:pk>/delete/", views.FileAttachmentDeleteView.as_view(), name="attachment_delete"),
    path("comments/", views.ProjectCommentListView.as_view(), name="comment_list"),
    path("projects/<int:project_id>/comments/create/", views.ProjectCommentCreateView.as_view(), name="comment_create"),
    path("comments/<int:pk>/edit/", views.ProjectCommentUpdateView.as_view(), name="comment_update"),
    path("comments/<int:pk>/delete/", views.ProjectCommentDeleteView.as_view(), name="comment_delete"),
    path("invoices/<int:pk>/create-payment-intent/", views.create_stripe_payment_intent, name="invoice_create_payment_intent"),
    path("stripe-webhook/", views.stripe_webhook, name="stripe_webhook"),
    path("recurring/", views.RecurringBillingListView.as_view(), name="recurring_list"),
    path("recurring/create/", views.RecurringBillingCreateView.as_view(), name="recurring_create"),
    path("recurring/<int:pk>/", views.RecurringBillingDetailView.as_view(), name="recurring_detail"),
    path("recurring/<int:pk>/edit/", views.RecurringBillingUpdateView.as_view(), name="recurring_update"),
    path("recurring/<int:pk>/delete/", views.RecurringBillingDeleteView.as_view(), name="recurring_delete"),
    path("recurring/<int:pk>/generate-invoice/", views.generate_recurring_invoice, name="recurring_generate_invoice"),
]
