# Generated by Django 4.2 on 2026-07-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_invoice_pdf_file'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('viewer', 'Viewer'), ('client', 'Client')], default='viewer', max_length=20)),
                ('can_delete', models.BooleanField(default=False, help_text='Allow deletion of records')),
                ('can_edit', models.BooleanField(default=True, help_text='Allow editing of records')),
                ('client', models.ForeignKey(blank=True, help_text='For client-facing users, link to their client account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='dashboard.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
