# Generated by Django 4.2 on 2026-07-24

from django.db import migrations, models
import django.contrib.contenttypes.fields
import django.contrib.contenttypes.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userprofile'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('status_change', 'Status Changed')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='auth.user')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'indexes': [
                    models.Index(fields=['content_type', 'object_id'], name='dashboard_a_content_8b3f_idx'),
                    models.Index(fields=['user'], name='dashboard_a_user_id_idx'),
                    models.Index(fields=['timestamp'], name='dashboard_a_timestam_idx'),
                ],
                'ordering': ['-timestamp'],
            },
        ),
    ]
