# Generated by Django 4.2 on 2026-07-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('hours', models.DecimalField(decimal_places=2, help_text='Hours worked', max_digits=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='dashboard.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='auth.user')),
            ],
            options={
                'verbose_name': 'Time Entry',
                'verbose_name_plural': 'Time Entries',
                'ordering': ['-date', '-created_at'],
                'indexes': [
                    models.Index(fields=['project'], name='dashboard_t_project_id_idx'),
                    models.Index(fields=['user'], name='dashboard_t_user_id_idx'),
                    models.Index(fields=['date'], name='dashboard_t_date_idx'),
                ],
            },
        ),
    ]
