# Generated by Django 5.2.16 on 2026-07-24 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_timeentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('file_type', models.CharField(choices=[('contract', 'Contract'), ('proposal', 'Proposal'), ('screenshot', 'Screenshot'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'File Attachment',
                'verbose_name_plural': 'File Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Comment',
                'verbose_name_plural': 'Project Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='dashboard_a_content_73f284_idx',
            old_name='dashboard_a_content_8b3f_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='dashboard_a_user_id_4bd247_idx',
            old_name='dashboard_a_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='dashboard_a_timesta_3a0d49_idx',
            old_name='dashboard_a_timestam_idx',
        ),
        migrations.RenameIndex(
            model_name='timeentry',
            new_name='dashboard_t_project_a01e48_idx',
            old_name='dashboard_t_project_id_idx',
        ),
        migrations.RenameIndex(
            model_name='timeentry',
            new_name='dashboard_t_user_id_62171b_idx',
            old_name='dashboard_t_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='timeentry',
            new_name='dashboard_t_date_4f0808_idx',
            old_name='dashboard_t_date_idx',
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboard.project'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboard.project'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fileattachment',
            index=models.Index(fields=['project'], name='dashboard_f_project_d8a0eb_idx'),
        ),
        migrations.AddIndex(
            model_name='fileattachment',
            index=models.Index(fields=['file_type'], name='dashboard_f_file_ty_456444_idx'),
        ),
        migrations.AddIndex(
            model_name='fileattachment',
            index=models.Index(fields=['uploaded_at'], name='dashboard_f_uploade_197593_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['project'], name='dashboard_p_project_75b3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['created_at'], name='dashboard_p_created_ba180c_idx'),
        ),
    ]
