# Generated by Django 5.2.16 on 2026-07-24 18:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_fileattachment_projectcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When the invoice was marked as paid', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_status',
            field=models.CharField(blank=True, help_text='Stripe payment status', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='RecurringBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this recurring billing (e.g., "Monthly Hosting")', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of services included')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Recurring amount', max_digits=12)),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('next_billing_date', models.DateField()),
                ('last_billed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_billings', to='dashboard.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_billings', to='dashboard.project')),
            ],
            options={
                'verbose_name': 'Recurring Billing',
                'verbose_name_plural': 'Recurring Billings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client'], name='dashboard_r_client__4599e2_idx'), models.Index(fields=['status'], name='dashboard_r_status_049b41_idx'), models.Index(fields=['next_billing_date'], name='dashboard_r_next_bi_df653d_idx')],
            },
        ),
    ]
